inserzioni/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'inserzioni'


urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^$', views.lista_prodotti, name='lista_prodotti'),
	url(r'^(?P<regione_slug>[-\w]+)/(?P<categoria_slug>[-\w]+)$', views.lista_prodotti, name='lista_prodotti_filtro_regione_categoria'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.dettaglio_prodotti, name='dettaglio_prodotti'),
	url(r'^crea_inserzione/', views.crea_inserzione, name='crea_inserzione'),
	url(r'^le_mie_inserzioni/', views.lista_mie_inserzioni, name='lista_mie_inserzioni'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/modifica$', views.modifica_prodotti, name='modifica_prodotti')
]

messaggi/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'messaggi'

urlpatterns = [
	url(r'^messaggi/$', login_required(views.DialogsView.as_view()), name='dialoghi'),
	url(r'^messaggi/create/(?P<user_id>\d+)/$', login_required(views.CreateDialogView.as_view()), name='crea_dialogo'),
	url(r'^messaggi/(?P<chat_id>\d+)/$', login_required(views.MessagesView.as_view()), name='messaggio')
]

ordini/urls.py
from django.conf.urls import url
from . import views

app_name = 'ordini'

urlpatterns = [
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/ordine$', views.aggiungi_ordine, name='aggiungi_ordine'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/ordine/completato$', views.acquisto_ordine, name='acquisto_ordine'),
	url(r'^storico_vendite/$', views.storico_vendite_ordine, name='storico_vendite_ordine'),
	url(r'^storico_acquisti/$', views.storico_acquisti_ordine, name='storico_acquisti_ordine')
]

progetto/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
	url('', include('inserzioni.urls')),
	url('', include('utenti.urls')),
    url('', include('ordini.urls')),
	url('', include('messaggi.urls')),
	url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inserzioni/models.py
from django.db import models
from django.http import HttpResponse
from django.urls import reverse
from django.template.defaultfilters import slugify
from utenti.models import Profile


class Categoria(models.Model):
    nome = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True ,db_index=True)
    orario_creazione = models.DateTimeField(auto_now_add=True)
    orario_aggiornamento = models.DateTimeField(auto_now=True)
 
    class Meta:
        ordering = ('nome', )
        verbose_name = 'catergoria'
        verbose_name_plural = 'categorie'
 
    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('inserzioni:lista_prodotti_filtro_regione_categoria', args=["all",self.slug])
		
		
		
		
class Regione(models.Model):
    nome = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True ,db_index=True)
    orario_creazione = models.DateTimeField(auto_now_add=True)
    orario_aggiornamento = models.DateTimeField(auto_now=True)
 
    class Meta:
        ordering = ('nome', )
        verbose_name = 'regione'
        verbose_name_plural = 'regioni'
 
    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('inserzioni:lista_prodotti_filtro_regione_categoria', args=[self.slug, "all"])
 
 
class Prodotto(models.Model):
	categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
	regione = models.ForeignKey(Regione, on_delete=models.CASCADE)
	user = models.ForeignKey(Profile, on_delete=models.CASCADE)
	nome = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	descrizione = models.TextField(blank=True)
	prezzo = models.DecimalField(max_digits=10, decimal_places=2)
	disponibilita = models.BooleanField(default=True)
	venduto = models.BooleanField(default=False)
	orario_creazione = models.DateTimeField(auto_now_add=True)
	orario_aggiornamento = models.DateTimeField(auto_now=True)
	immagine = models.ImageField(upload_to='media/%Y/%m/%d', blank=True)
 
	class Meta:
		ordering = ('-orario_creazione', )
		verbose_name = 'prodotto'
		verbose_name_plural = 'prodotti'
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.nome
		
	def save(self, *args, **kwargs):
		self.slug = slugify(self.nome)
		super(Prodotto, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('inserzioni:dettaglio_prodotti', args=[self.id, self.slug])
		
	def get_absolute_url_for_my_list(self):
		return reverse('inserzioni:modifica_prodotti', args=[self.id, self.slug])

inserzioni/forms.py
from django import forms
from decimal import *
from django.core.validators import MaxValueValidator, MinValueValidator
from inserzioni.models import Categoria,Regione,Prodotto


class FiltroForm(forms.Form):
	regione = forms.ModelChoiceField(queryset = Regione.objects.all(), empty_label="tutto", required=False)
	categoria = forms.ModelChoiceField(queryset = Categoria.objects.all(), empty_label="tutto", required=False)
		
		
class InserisciInserzioneForm(forms.Form):
	regione = forms.ModelChoiceField(queryset = Regione.objects.all(), empty_label=None)
	categoria = forms.ModelChoiceField(queryset = Categoria.objects.all(), empty_label=None)
	titolo = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "Inserisci titolo.", 'maxlength':200}))
	descrizione = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', "placeholder": "Inserisci una descrizione del prodotto."}))
	prezzo = forms.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
	disponibilita = forms.BooleanField(required=False, initial = True)
	immagine = forms.ImageField(required=False)

class ModificaInserzioneFiltroForm(forms.Form):
	CHOICES=[('tutto','Tutto'),
			('venduti','Venduti'),
			('disponibili','Disponibili')]

	filtro = forms.ChoiceField(choices=CHOICES)

inserzioni/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Categoria,Regione,Prodotto
from utenti.models import Profile
from .forms import *



def lista_prodotti(request,regione_slug=None, categoria_slug=None):
	prodotti = Prodotto.objects.filter(disponibilita=True, venduto=False)
	categoria = Categoria.objects.all()
	regione = Regione.objects.all()
		
	if request.method == 'POST':
		form = FiltroForm(request.POST)
		if form.is_valid():
			categoria_form = "tutto"
			regione_form = "tutto"
			
			if (form.cleaned_data['categoria'] != None):
				categoria_form = form.cleaned_data['categoria'].slug
				
			if (form.cleaned_data['regione'] != None):
				regione_form = form.cleaned_data['regione'].slug
				
			return HttpResponseRedirect(reverse('inserzioni:lista_prodotti_filtro_regione_categoria', args=(regione_form,categoria_form,)))
	else:
		if categoria_slug and regione_slug:
			if(categoria_slug != "tutto" and regione_slug!="tutto"):
				categoria = get_object_or_404(Categoria, slug=categoria_slug)
				regione = get_object_or_404(Regione, slug=regione_slug)
				prodotti = Prodotto.objects.filter(categoria=categoria, regione=regione)
			elif (categoria_slug == "tutto" and regione_slug!="tutto"):
				regione = get_object_or_404(Regione, slug=regione_slug)
				prodotti = Prodotto.objects.filter(regione=regione)
			elif (categoria_slug != "tutto" and regione_slug=="tutto"):
				categoria = get_object_or_404(Categoria, slug=categoria_slug)
				prodotti = Prodotto.objects.filter(categoria=categoria)
		form = FiltroForm(initial={'categoria': categoria, 'regione':regione})
		return render(request, 'inserzioni/list.html', { 'form': form, 'prodotti': prodotti, 'categoria':categoria, 'regione':regione})

def dettaglio_prodotti(request, id, slug):
	prodotto = get_object_or_404(Prodotto, id=id, slug=slug, disponibilita=True, venduto=False)
	compratore = False
	venditore = False
	
	
	if request.user.is_authenticated():
		if prodotto.user.user.username != request.user.username:
			compratore = True;
		else:
			venditore = True;
	
	context = {
		'prodotto': prodotto,
		'compratore': compratore,
		'venditore': venditore
	}
	return render(request, 'inserzioni/detail.html', context)


@login_required
def crea_inserzione(request):
	if request.method == 'POST':
		form = InserisciInserzioneForm(request.POST, request.FILES)
		if form.is_valid():
			user = request.user
			categoria = form.cleaned_data['categoria'].slug
			regione = form.cleaned_data['regione'].slug
			nome = form.cleaned_data['titolo']
			descrizione = form.cleaned_data['descrizione']
			prezzo = form.cleaned_data['prezzo']
			disponibilita = form.cleaned_data['disponibilita']
			immagine = form.cleaned_data['immagine']
			p = Prodotto.objects.create(categoria=Categoria.objects.get(slug=categoria),
						regione=Regione.objects.get(slug=regione),
						user=Profile.objects.get(user=user),
						nome=nome,
						descrizione=descrizione,
						prezzo=prezzo,
						disponibilita=disponibilita,
						immagine=immagine)
			p.save()
       
			return redirect('inserzioni:lista_prodotti')
	else:
		form = InserisciInserzioneForm(initial={'prezzo': 0.00})
		
	return render(request, 'inserzioni/crea_inserzione.html', { 'form': form })
		
@login_required	
def lista_mie_inserzioni(request):
	prodotti = Prodotto.objects.filter(user=Profile.objects.get(user=request.user), venduto=False)

	if request.method == 'POST':
		form = ModificaInserzioneFiltroForm(request.POST)
		if form.is_valid():
			filtro = form.cleaned_data['filtro']
			if filtro == 'venduti':
				prodotti = Prodotto.objects.filter(user=Profile.objects.get(user=request.user), disponibilita=False)
			elif filtro == 'disponibili':
				prodotti = Prodotto.objects.filter(user=Profile.objects.get(user=request.user), disponibilita=True)
	else:
		form = ModificaInserzioneFiltroForm()
	return render(request, 'inserzioni/le_mie_inserzioni.html', { 'prodotti': prodotti, 'form':form})

@login_required
def modifica_prodotti(request, id, slug):
	prodotto = get_object_or_404(Prodotto, user=Profile.objects.get(user=request.user), id=id, slug=slug, venduto=False)

	if request.method == 'POST':
		form = InserisciInserzioneForm(request.POST, request.FILES)
		if form.is_valid():
			prodotto.categoria = Categoria.objects.get(slug=form.cleaned_data['categoria'].slug)
			prodotto.regione = Regione.objects.get(slug=form.cleaned_data['regione'].slug)
			prodotto.nome = form.cleaned_data['titolo']
			prodotto.descrizione = form.cleaned_data['descrizione']
			prodotto.prezzo = form.cleaned_data['prezzo']
			prodotto.disponibilita = form.cleaned_data['disponibilita']
			prodotto.immagine = form.cleaned_data['immagine']
			prodotto.save()
       
			return redirect('inserzioni:lista_mie_inserzioni')
		else:
			return HttpResponse('Data not valid')		
		
	else:
		categoria = Categoria.objects.get(slug=prodotto.categoria.slug)
		form = InserisciInserzioneForm(initial={'categoria': (prodotto.categoria.slug, prodotto.categoria.nome), 'regione': (prodotto.regione.slug, prodotto.regione.nome), 'titolo': prodotto.nome, 'descrizione':prodotto.descrizione, 'prezzo':prodotto.prezzo, 'disponibilita':prodotto.disponibilita, 'immagine':prodotto.immagine})
		return render(request, 'inserzioni/modifica_inserzione.html', {'form': form}) 
	
	
	

inserzioni/templates/inserzioni/crea_inserzione.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Crea Inserzione
{% endblock %}

{% block content %}
	<div class="col-sm-3 blog-main">
		<h3> CREA INSERZIONE </h3><br></br>
		<form method="post" enctype="multipart/form-data">{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Applica" />
		</form>
	</div>
{% endblock %}

inserzioni/templates/inserzioni/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if categoria %}{{ categoria.name }} {% else %} Prodotti {% endif %}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 blog-main">
      <div class="blog-post">
        <div class="row">
          <div class="card">
            <div class="card-body">
              <div class="col-md-6 text-right">
                <img src="{% if prodotto.immagine %} {{ prodotto.immagine.url }} {% else %} {% static 'inserzioni/img/default.jpg' %} {% endif %}" alt="..." style="height: 200px; width: auto">
              </div>
              <div class="col-md-6" style="padding-left: 20px">
                <h3>{{ prodotto.nome }} [<strong>{{ prodotto.user }}</strong>]</h3>
                <strong> Recensioni utente {{prodotto.user.vote_average}} </strong>(n.voti:{{prodotto.user.vote_count}})</h5><br>
                {% if prodotto.user.phone_number %}
                	<h6>Tel. {{prodotto.user.phone_number}} </h6>
                {% endif %}
                <h6><a href="{{ prodotto.categoria.get_absolute_url }}">{{ prodotto.categoria }}</a></h6>
                <h6><a href="{{ prodotto.regione.get_absolute_url }}">{{ prodotto.regione }}</a></h6>
                <p class="text-muted">{{ prodotto.prezzo }} EURO</p>
                <p>{{ prodotto.descrizione|safe|linebreaksbr }}</p>
                {% if compratore %}
                  <form method="post" action="{% url "ordini:aggiungi_ordine"  prodotto.id prodotto.slug%}">{% csrf_token %}
                  {{ form.as_p }}
                  <input type="submit" value="Compra" class="btn btn-primary" style="background-color:#FF7F50;border-color:#FF7F50">
                  </form>
                  <br><form method="get" action="{% url "messaggi:crea_dialogo"  prodotto.user.id %}">{% csrf_token %}
                  <input type="submit" value="Contatta" class="btn btn-primary" style="background-color:#FF7F50;border-color:#FF7F50">
                  </form>
                {% endif %}
                {% if venditore%}
                  <form method="get" action="{% url "inserzioni:modifica_prodotti"  prodotto.id prodotto.slug%}">{% csrf_token %}
                  {{ form.as_p }}
                  <input type="submit" value="Modifica" class="btn btn-primary" style="background-color:#FF7F50;border-color:#FF7F50">
                  </form>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.blog-post -->
    </div>
    <!-- /.blog-main -->
  </div>
  <!-- /.row -->
</div>
<!-- /.container -->
{% endblock %}

inserzioni/templates/inserzioni/le_mie_inserzioni.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Le mie inserzioni
{% endblock %}

{% block content %} 

	<div class="container-fluid">
		<div class="row"> 
		
			<form method="post">{% csrf_token %}
				{{ form.as_p }}
				<input type="submit" value="Applica" />
			</form>

	
			<div class="col-sm-12 blog-main" style="margin-top:3%">
			
			{% if categoria or regione%} <h3>Filtri: {{regione.nome}},{{categoria.nome}} </h3 > {% endif %}

				<div class="blog-post" style="margin-top:2%">
					<div class="row">
						{% for prodotto in prodotti %}
							<div class="col-md-4">
							<div class="thumbnail">
								<a href="{{ prodotto.get_absolute_url_for_my_list }}">
									<img src="{% if prodotto.immagine %} {{ prodotto.immagine.url }} {% else %} {% static 'inserzioni/img/default.jpg' %} {% endif %}" alt="..." style="height: 400px; width: auto">
								</a>
								<div class="caption">
									<h3 class="text-center">
										<a style= "display: block;   width: 600px;   overflow: hidden;   white-space: nowrap;   text-overflow: ellipsis;" href="{{ prodotto.get_absolute_url_for_my_list }}">{{ prodotto.nome }}</a>
									</h3>
									<p class="text-center">{{ prodotto.prezzo }} EURO</p>
								</div>
							</div>
							</div>
						{% endfor %}
					</div>


				</div><!-- /.blog-post -->

			</div><!-- /.blog-main -->
			
		</div><!-- /.row -->

	</div><!-- /.container -->
{% endblock %}

inserzioni/templates/inserzioni/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Lista Prodotti
{% endblock %}

{% block content %} 

	<div class="container-fluid">
		<div class="row"> 
		
			<form method="post">{% csrf_token %}
				<label>Filtro</label>
				{{ form.as_p }}
				<input type="submit" value="Applica" />
			</form>

	
			<div class="col-sm-12 blog-main" style="margin-top:3%">

				<div class="blog-post" style="margin-top:2%">
					<div class="row">
						{% for prodotto in prodotti %}
							<div class="col-md-4">
							<div class="thumbnail">
								<a href="{{ prodotto.get_absolute_url }}">
									<img src="{% if prodotto.immagine %} {{ prodotto.immagine.url }} {% else %} {% static 'inserzioni/img/default.jpg' %} {% endif %}" alt="..." style="height: 400px; width: auto">
								</a>
								<div class="caption">
									<h3 class="text-center">
										<a style= "display: block;   width: 600px;   overflow: hidden;   white-space: nowrap;   text-overflow: ellipsis;" href="{{ prodotto.get_absolute_url }}">{{ prodotto.nome }}</a>
									</h3>
									<p class="text-center">{{ prodotto.prezzo }} EURO</p>
								</div>
							</div>
							</div>
						{% endfor %}
					</div>


				</div><!-- /.blog-post -->

			</div><!-- /.blog-main -->
			
		</div><!-- /.row -->

	</div><!-- /.container -->
{% endblock %}

inserzioni/templates/inserzioni/modifica_inserzione.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Modifica Inserzione
{% endblock %}

{% block content %}
	<div class="col-sm-3 blog-main">
		<h3> MODIFICA INSERZIONE </h3><br></br>
		<form method="post" enctype="multipart/form-data">{% csrf_token %}
				{{ form.as_p }}
				<input type="submit" value="Applica" />
		</form>
	</div>
{% endblock %}