ordini/urls.py
from django.conf.urls import url
from . import views

app_name = 'ordini'

urlpatterns = [
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/ordine$', views.aggiungi_ordine, name='aggiungi_ordine'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/ordine/completato$', views.acquisto_ordine, name='acquisto_ordine'),
	url(r'^storico_vendite/$', views.storico_vendite_ordine, name='storico_vendite_ordine'),
	url(r'^storico_acquisti/$', views.storico_acquisti_ordine, name='storico_acquisti_ordine')
]

progetto/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
	url('', include('inserzioni.urls')),
	url('', include('utenti.urls')),
    url('', include('ordini.urls')),
	url('', include('messaggi.urls')),
	url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordini/models.py
from django.db import models
from django.http import HttpResponse
from django.urls import reverse

from utenti.models import Profile
from inserzioni.models import Prodotto


class Ordine(models.Model):
	compratore = models.ForeignKey(Profile, related_name="compratore", on_delete=models.CASCADE)
	venditore = models.ForeignKey(Profile, related_name="venditore", on_delete=models.CASCADE)
	prodotto = models.ForeignKey(Prodotto, on_delete=models.CASCADE)
	prezzo = models.DecimalField(max_digits=10, decimal_places=2)
	orario_acquisto = models.DateTimeField(auto_now_add=True)
 
	class Meta:
		ordering = ('orario_acquisto', )
		verbose_name = 'ordine'
		verbose_name_plural = 'ordini'

ordini/forms.py
from django import forms

class FiltroOrdineForm(forms.Form):

	giorni = (
			(0,'Tutto'),
			(1,'1 giorno'),
			(30,'30 giorni'),
			(60,'60 giorni')
			)
	filtro = forms.ChoiceField(choices=giorni, label="Intervallo giorni")
	

ordini/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from inserzioni.models import Prodotto
from utenti.models import Profile
from .models import Ordine
from ordini.forms import FiltroOrdineForm
from datetime import datetime, timedelta
from django.utils import timezone

@require_POST
@login_required
def aggiungi_ordine(request, id, slug):
	prodotto = get_object_or_404(Prodotto, id=id, slug=slug)

	prezzo_totale = prodotto.prezzo
	user = User.objects.get(username=prodotto.user)
	venditore = Profile.objects.get(user=user)
	compratore = Profile.objects.get(user=request.user)

	if (compratore != venditore):
		return render(request, 'ordini/dettaglio_ordine.html', {'prodotto':prodotto, 'prezzo_totale':prezzo_totale})
	else:
		return redirect ('inserzioni:lista_prodotti')


@require_POST
@login_required
def acquisto_ordine(request, id, slug):
	prodotto = get_object_or_404(Prodotto, id=id, slug=slug)

	prezzo_totale = prodotto.prezzo
	user = User.objects.get(username=prodotto.user)
	venditore = Profile.objects.get(user=user)
	compratore = Profile.objects.get(user=request.user)

	if 'conferma_acquisto' in request.POST:
		if (compratore != venditore and prodotto.disponibilita):
			o = Ordine.objects.create(venditore=venditore,
						compratore=compratore,
						prodotto=prodotto,
						prezzo=prodotto.prezzo
						)
			o.save()

			prodotto.disponibilita = False
			prodotto.venduto = True
			prodotto.save()
			
			request.session['last_view'] = "ordine"
			request.session['user_name'] = venditore.user.username
			return HttpResponseRedirect(reverse('utenti:votazione', args=(venditore.user.username,)))

		
	return redirect ('inserzioni:lista_prodotti')


@login_required
def storico_vendite_ordine(request):
	guadagno = 0
	me = get_object_or_404(Profile,user=request.user)
	ordini = Ordine.objects.filter(venditore=me)
	
	if request.method == 'POST':
		form = FiltroOrdineForm(request.POST)
		if form.is_valid():
			giorni = form.cleaned_data['filtro']
			if giorni != "0":
				#print (datetime.today() - timedelta(days=int(giorni)))
				ordini = Ordine.objects.filter(orario_acquisto__gt=datetime.today()-timedelta(days=int(giorni)), venditore=me)
				
				for o in ordini:
					print (o.orario_acquisto)
					guadagno = guadagno + o.prezzo
				
				print (giorni)
			else:
				for o in ordini:
					guadagno = guadagno + o.prezzo
	else:
		for o in ordini:
			print (o.orario_acquisto)
			guadagno = guadagno + o.prezzo
		
		form = FiltroOrdineForm(initial={'filtro': 0})
		
	return render(request, 'ordini/storico_vendite.html', {'form': form, 'ordini':ordini, 'guadagno':guadagno})
	
	
@login_required
def storico_acquisti_ordine(request):
	me = get_object_or_404(Profile,user=request.user)
	ordini = Ordine.objects.filter(compratore=me)
	
	if request.method == 'POST':
		form = FiltroOrdineForm(request.POST)
		if form.is_valid():
			giorni = form.cleaned_data['filtro']
			if giorni != "0":
				ordini = Ordine.objects.filter(orario_acquisto__gt=datetime.today()-timedelta(days=int(giorni)), compratore=me)		
	else:
		form = FiltroOrdineForm(initial={'filtro': 0})
		
	return render(request, 'ordini/storico_acquisti.html', {'form': form, 'ordini':ordini})



	
	

ordini/templates/ordini/dettaglio_ordine.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Conferma l'ordine
{% endblock %}


{% block content %}
    <div class="container" role="form">
        <div class="row">
            <table class="table table-striped table-hover">
                <thead style="background-color: #FF7F50">
                    <tr>
                        <th>Immagine</th>
                        <th>Prodotto</th>
                        <th>Prezzo</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <a href="{{ prodotto.get__absolute_url }}">
                                <img src="{% if prodotto.immagine %} {{ prodotto.immagine.url }} {% else %} {% static 'inserzioni/img/default.jpg' %} {% endif %}" alt="..." style="height: 120px; width: auto">
                            </a>
                        </td>
                        <td>{{ prodotto.nome }}</td>
                        <td>{{ prodotto.prezzo }} EURO</td>
                    </tr>
                <tr style="background-color: #FF7F50">
                    <td colspan="3"></td>
                </tr>
                </tbody>
            </table>
		<div class="text-right">		
			<form action="{% url "ordini:acquisto_ordine" prodotto.id prodotto.slug %}" method="post">{% csrf_token %}
				<button style="background-color:#FF7F50;border-color:#FF7F50" type="submit" name="conferma_acquisto" value="Conferma acquisto" class="btn btn-primary">Conferma acquisto</button>
				<button name="annulla_acquisto" class="btn btn-default">Annulla acquisto</button>
			</form>
		</div>
        </div>
    </div>
{% endblock %}

ordini/templates/ordini/storico_acquisti.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Conferma l'ordine
{% endblock %}


{% block content %}
	<form method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Ok">
	</form>
    <div class="container" role="form">
        <div class="row" style="margin-top: 6%">
            {% if ordini|length %}
                <table class="table table-striped table-hover">
                    <thead style="background-color: #FF7F50">
                        <tr>
                            <th>Immagine</th>
                            <th>Prodotto</th>
                            <th>Prezzo</th>
    						<th>Venduto da</th>
    						<th>Comprato il</th>
                        </tr>
                    </thead>
                    <tbody>
    				{% for ordine in ordini %}
                        <tr>
                            <td>
                                <a>
                                    <img src="{% if ordine.prodotto.immagine %} {{ ordine.prodotto.immagine.url }} {% else %} {% static 'inserzioni/img/default.jpg' %} {% endif %}" alt="..." style="height: 120px; width: auto">
                                </a>
                            </td>
                            <td>{{ ordine.prodotto.nome }}</td>
                            <td>{{ ordine.prodotto.prezzo }} EURO</td>
    						<td>{{ ordine.venditore }}</td>
    						<td>{{ ordine.orario_acquisto }}</td>
                        </tr>
    					<tr style="background-color: #FF7F50">
    						<td colspan="5"></td>
    					</tr>
    				{% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="panel panel-body">Non hai ordini con i filtri richiesti</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

ordini/templates/ordini/storico_vendite.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Conferma l'ordine
{% endblock %}


{% block content %}
	<form method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Ok">
	</form>
	<h3> Guadagno: {{guadagno}} EURO </h3>
    <div class="container" role="form">
        <div class="row" style="margin-top: 6%">
            {% if ordini|length %}
                <table class="table table-striped table-hover">
                    <thead style="background-color: #FF7F50">
                        <tr>
                            <th>Immagine</th>
                            <th>Prodotto</th>
                            <th>Prezzo</th>
    						<th>Comprato da</th>
    						<th>Venduto il</th>
                        </tr>
                    </thead>
                    <tbody>
    				{% for ordine in ordini %}
                        <tr>
                            <td>
                                <a>
                                    <img src="{% if ordine.prodotto.immagine %} {{ ordine.prodotto.immagine.url }} {% else %} {% static 'inserzioni/img/default.jpg' %} {% endif %}" alt="..." style="height: 120px; width: auto">
                                </a>
                            </td>
                            <td>{{ ordine.prodotto.nome }}</td>
                            <td>{{ ordine.prodotto.prezzo }} EURO</td>
    						<td>{{ ordine.compratore }}</td>
    						<td>{{ ordine.orario_acquisto }}</td>
                        </tr>
    					<tr style="background-color: #FF7F50">
    						<td colspan="5"></td>
    					</tr>
    				{% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="panel panel-body">Non hai ordini con i filtri richiesti</div>
            {% endif %}
        </div>
    </div>
{% endblock %}