inserzioni/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'inserzioni'


urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^$', views.lista_prodotti, name='lista_prodotti'),
	url(r'^(?P<regione_slug>[-\w]+)/(?P<categoria_slug>[-\w]+)$', views.lista_prodotti, name='lista_prodotti_filtro_regione_categoria'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.dettaglio_prodotti, name='dettaglio_prodotti'),
	url(r'^crea_inserzione/', views.crea_inserzione, name='crea_inserzione'),
	url(r'^le_mie_inserzioni/', views.lista_mie_inserzioni, name='lista_mie_inserzioni'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/modifica$', views.modifica_prodotti, name='modifica_prodotti')
]

messaggi/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'messaggi'

urlpatterns = [
	url(r'^messaggi/$', login_required(views.DialogsView.as_view()), name='dialoghi'),
	url(r'^messaggi/create/(?P<user_id>\d+)/$', login_required(views.CreateDialogView.as_view()), name='crea_dialogo'),
	url(r'^messaggi/(?P<chat_id>\d+)/$', login_required(views.MessagesView.as_view()), name='messaggio')
]

ordini/urls.py
from django.conf.urls import url
from . import views

app_name = 'ordini'

urlpatterns = [
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/ordine$', views.aggiungi_ordine, name='aggiungi_ordine'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/ordine/completato$', views.acquisto_ordine, name='acquisto_ordine'),
	url(r'^storico_vendite/$', views.storico_vendite_ordine, name='storico_vendite_ordine'),
	url(r'^storico_acquisti/$', views.storico_acquisti_ordine, name='storico_acquisti_ordine')
]

progetto/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
	url('', include('inserzioni.urls')),
	url('', include('utenti.urls')),
    url('', include('ordini.urls')),
	url('', include('messaggi.urls')),
	url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utenti/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from utenti import views as utenti_views

app_name = 'utenti'

urlpatterns = [
    url(r'^login/$', auth_views.login,{'template_name': 'utenti/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', utenti_views.signup, name='signup'),
    url(r'^account_activation_sent/$', utenti_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', utenti_views.activate, name='activate'),
	url(r'^votazione/(?P<username>[\w.@+-]+)/$', utenti_views.votazione, name='votazione'),
	url(r'^modifica/$', utenti_views.modifica_profilo, name='modifica_profilo')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CompraVendita{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'inserzioni/css/bootstrap.min.css' %}">
</head>
<body>
{% include "navbar.html" %}
<div style="margin-top: 4%">
	{% if nuovi_dialoghi_count > 0 %}
		<div class="nav nav-tabs navbar-right" style="margin-right: 2%">
		    <div class="pull-right">
		         <button class="btn btn-info pull-right" style="background-color:#FF7F50;border-color:#FF7F50">
		                <a href="{% url 'messaggi:dialoghi' %}" style="color: #ffffff">
		                	{% if nuovi_dialoghi_count == 1 %}
		                    	Hai {{ nuovi_dialoghi_count }} conversazione non letta
		                	{% else %}
		                		Hai {{ nuovi_dialoghi_count }} conversazioni non lette
		                	{% endif %}
		                </a>
					{% endif %}
		         </button>
		    </div>
		</div>
	{% block content %}

	{% endblock %}

</div>

<script src="{% static 'inserzioni/js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'inserzioni/js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

</body>
</html>

templates/navbar.html
{% load static %}
<script>
function startTime() {
    var today = new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('orologio').innerHTML =
    h + ":" + m + ":" + s;
    var t = setTimeout(startTime, 500);
}
function checkTime(i) {
    if (i < 10) {i = "0" + i};
    return i;
}
</script>

<body onload="startTime()">
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #FF7F50;">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'inserzioni:lista_prodotti' %}" style="color: #ffffff">Home</a>
	      {% if request.user.is_authenticated %}
	        <a class="navbar-brand" href="{% url 'inserzioni:crea_inserzione' %}" style="color: #ffffff">Crea Inserzione</a>
	        <a class="navbar-brand" href="{% url 'inserzioni:lista_mie_inserzioni' %}" style="color: #ffffff">Le mie inserzioni</a>
	        <a class="navbar-brand" href="{% url 'ordini:storico_vendite_ordine' %}" style="color: #ffffff">Storico vendite</a>
	        <a class="navbar-brand" href="{% url 'ordini:storico_acquisti_ordine' %}" style="color: #ffffff">Storico acquisti</a>
	        <a class="navbar-brand" href="{% url 'messaggi:dialoghi' %}" style="color: #ffffff">Messaggi</a>
	      {% endif %}
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        
	          {% if request.user.is_authenticated %}
				<li><a style="color: #004c99" id="orologio"></a></li>
	            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
	            <ul class="dropdown-menu">
	              <li><a href="{% url 'utenti:modifica_profilo' %}">Modifica</a></li>
	              <li><a href="{% url 'utenti:logout' %}">Logout</a></li>
	            </ul>
	          {% else %}
	              <li class="divider"></li>
	              <li><a style="color: #004c99" id="orologio"></a></li>
	              <li><a href="{% url 'utenti:login' %}" style="color: #ffffff">Login</a></li>
	              <li><a href="{% url 'utenti:signup' %}" style="color: #ffffff">Registrati</a></li>
	            </ul>
	          {% endif %}
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>
</body>